export const scoreMultiplierArrays = [
  ['tw', '', '', 'dl', '', '', '', 'tw', '', '', '', 'dl', '', '', 'tw'],
  ['', 'dw', '', '', '', 'tl', '', '', '', 'tl', '', '', '', 'dw', ''],
  ['', '', 'dw', '', '', '', 'dl', '', 'dl', '', '', '', 'dw', '', ''],
  ['dl', '', '', 'dw', '', '', '', 'dl', '', '', '', 'dw', '', '', 'dl'],
  ['', '', '', '', 'dw', '', '', '', '', '', 'dw', '', '', '', ''],
  ['', 'tl', '', '', '', 'tl', '', '', '', 'tl', '', '', '', 'tl', ''],
  ['', '', 'dl', '', '', '', 'dl', '', 'dl', '', '', '', 'dl', '', ''],
  ['tw', '', '', 'dl', '', '', '', 'dw', '', '', '', 'dl', '', '', 'tw'],
]

export const INITIAL_BOARD_STATE = [
  [
    // ROW 1
    [
      { letter: '', scoreMultiplier: 'tw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'tw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'tw', isBlank: false, isFocused: false },
    ],
    // ROW 2
    [
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'tl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'tl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
    ],
    // ROW 3
    [
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
    ],
    // ROW 4
    [
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
    ],
    // ROW 5
    [
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
    ],
    // ROW 6
    [
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'tl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'tl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'tl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'tl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
    ],
    // ROW 7
    [
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
    ],
    // ROW 8
    [
      { letter: '', scoreMultiplier: 'tw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'tw', isBlank: false, isFocused: false },
    ],
    // ROW 9
    [
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
    ],
    // ROW 10
    [
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'tl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'tl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'tl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'tl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
    ],
    // ROW 11
    [
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
    ],
    // ROW 12
    [
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
    ],
    // ROW 13
    [
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
    ],
    // ROW 14
    [
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'tl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'tl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
    ],
    // ROW 15
    [
      { letter: '', scoreMultiplier: 'tw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'tw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'tw', isBlank: false, isFocused: false },
    ],
  ],
]

export const STARTING_LETTER_COUNTS = {
  a: 9,
  b: 2,
  c: 2,
  d: 4,
  e: 12,
  f: 2,
  g: 3,
  h: 2,
  i: 9,
  j: 1,
  k: 1,
  l: 4,
  m: 2,
  n: 6,
  o: 8,
  p: 2,
  q: 1,
  r: 6,
  s: 4,
  t: 6,
  u: 4,
  v: 2,
  w: 2,
  x: 1,
  y: 2,
  z: 1,
  ' ': 2,
}
