export const scoreMultiplierArrays = [
  ['tw', '', '', 'dl', '', '', '', 'tw', '', '', '', 'dl', '', '', 'tw'],
  ['', 'dw', '', '', '', 'tl', '', '', '', 'tl', '', '', '', 'dw', ''],
  ['', '', 'dw', '', '', '', 'dl', '', 'dl', '', '', '', 'dw', '', ''],
  ['dl', '', '', 'dw', '', '', '', 'dl', '', '', '', 'dw', '', '', 'dl'],
  ['', '', '', '', 'dw', '', '', '', '', '', 'dw', '', '', '', ''],
  ['', 'tl', '', '', '', 'tl', '', '', '', 'tl', '', '', '', 'tl', ''],
  ['', '', 'dl', '', '', '', 'dl', '', 'dl', '', '', '', 'dl', '', ''],
  ['tw', '', '', 'dl', '', '', '', 'dw', '', '', '', 'dl', '', '', 'tw'],
]

export const initialBoardState = [
  [
    // ROW 1
    [
      { letter: '', scoreMultiplier: 'tw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'tw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'tw', isBlank: false, isFocused: false },
    ],
    // ROW 2
    [
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'tl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'tl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
    ],
    // ROW 3
    [
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
    ],
    // ROW 4
    [
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
    ],
    // ROW 5
    [
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
    ],
    // ROW 6
    [
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'tl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'tl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'tl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'tl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
    ],
    // ROW 7
    [
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
    ],
    // ROW 8
    [
      { letter: '', scoreMultiplier: 'tw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'tw', isBlank: false, isFocused: false },
    ],
    // ROW 9
    [
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
    ],
    // ROW 10
    [
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'tl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'tl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'tl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'tl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
    ],
    // ROW 11
    [
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
    ],
    // ROW 12
    [
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
    ],
    // ROW 13
    [
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
    ],
    // ROW 14
    [
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'tl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'tl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
    ],
    // ROW 15
    [
      { letter: '', scoreMultiplier: 'tw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'tw', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'dl', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: '', isBlank: false, isFocused: false },
      { letter: '', scoreMultiplier: 'tw', isBlank: false, isFocused: false },
    ],
  ],
]
